package com.zakary.qingblog.mapper;

import com.zakary.qingblog.domain.BlogPraise;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface BlogPraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer blogPraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    int insert(BlogPraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    BlogPraise selectByPrimaryKey(Integer blogPraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    List<BlogPraise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogPraise record);

    void delBlogPraiseByUserIdBlogId(BlogPraise blogPraise);

    int selectByUserIdBlogId(BlogPraise blogPraise);
}