package com.zakary.qingblog.mapper;

import com.zakary.qingblog.domain.BlogPraise;
import java.util.List;

public interface BlogPraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer blogPraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    int insert(BlogPraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    BlogPraise selectByPrimaryKey(Integer blogPraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    List<BlogPraise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_praise
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogPraise record);
}