package com.zakary.qingblog.mapper;

import com.zakary.qingblog.domain.Comment;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Mapper
@Repository
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    Comment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Comment record);

    List<Map<String,Object>> selectAllByBlogId(@Param("blogId") int blogId, @Param("pageNo") int pageNo, @Param("pageSize") int pageSize);

    List<Map<String,Object>> selectChildCommentByParentId(@Param("parentCommentId")int parentCommentId,@Param("pageNo") int pageNo,@Param("pageSize")int pageSize);

    Map<String,Object> selectByCommentByCommentId(@Param("commentId")int commentId);
}