package com.zakary.qingblog.mapper;

import com.zakary.qingblog.domain.Favorites;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface FavoritesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("favoritesId") Integer favoritesId, @Param("blogId") Integer blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    int insert(Favorites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    Favorites selectByPrimaryKey(@Param("favoritesId") Integer favoritesId, @Param("blogId") Integer blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    List<Favorites> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Favorites record);

    void delFavoritesByFavoritesId(@Param("favoritesId") int favoritesId);

    int selectStarStatus(@Param("userId") int userId,@Param("blogId") int blogId);

    int selectFavoritesIdByUserIdBlogId(@Param("userId") int userId,@Param("blogId") int blogId);

}