package com.zakary.qingblog.mapper;

import com.zakary.qingblog.domain.Favorites;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavoritesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("blogId") Integer blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    int insert(Favorites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    Favorites selectByPrimaryKey(@Param("userId") Integer userId, @Param("blogId") Integer blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    List<Favorites> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Favorites record);
}