package com.zakary.qingblog.domain;

import org.springframework.stereotype.Repository;

import java.io.Serializable;

@Repository
public class CommentPraise implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_praise.comment_praise_id
     *
     * @mbg.generated
     */
    private Integer commentPraiseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_praise.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_praise.comment_id
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment_praise
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_praise.comment_praise_id
     *
     * @return the value of comment_praise.comment_praise_id
     *
     * @mbg.generated
     */
    public Integer getCommentPraiseId() {
        return commentPraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_praise.comment_praise_id
     *
     * @param commentPraiseId the value for comment_praise.comment_praise_id
     *
     * @mbg.generated
     */
    public void setCommentPraiseId(Integer commentPraiseId) {
        this.commentPraiseId = commentPraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_praise.user_id
     *
     * @return the value of comment_praise.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_praise.user_id
     *
     * @param userId the value for comment_praise.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_praise.comment_id
     *
     * @return the value of comment_praise.comment_id
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_praise.comment_id
     *
     * @param commentId the value for comment_praise.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_praise
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentPraiseId=").append(commentPraiseId);
        sb.append(", userId=").append(userId);
        sb.append(", commentId=").append(commentId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}