package com.zakary.qingblog.domain;

import org.springframework.stereotype.Repository;

import java.io.Serializable;

@Repository
public class FriendList implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_list.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_list.friend_id
     *
     * @mbg.generated
     */
    private Integer friendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_list.friend_remark
     *
     * @mbg.generated
     */
    private String friendRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friend_list
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_list.user_id
     *
     * @return the value of friend_list.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_list.user_id
     *
     * @param userId the value for friend_list.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_list.friend_id
     *
     * @return the value of friend_list.friend_id
     *
     * @mbg.generated
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_list.friend_id
     *
     * @param friendId the value for friend_list.friend_id
     *
     * @mbg.generated
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_list.friend_remark
     *
     * @return the value of friend_list.friend_remark
     *
     * @mbg.generated
     */
    public String getFriendRemark() {
        return friendRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_list.friend_remark
     *
     * @param friendRemark the value for friend_list.friend_remark
     *
     * @mbg.generated
     */
    public void setFriendRemark(String friendRemark) {
        this.friendRemark = friendRemark == null ? null : friendRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_list
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", friendId=").append(friendId);
        sb.append(", friendRemark=").append(friendRemark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}